version: '3.9'

services:
  postgres:
    image: 'postgres'
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./adapter/persistence/db-model/src/db/create_initial_tables.sql:/docker-entrypoint-initdb.d/init.sql